CREATE TABLE `Screws` (
	`Id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Color` TEXT NOT NULL,
	`Description` TEXT,
	`Price` DECIMAL(8, 2) NOT NULL
);
CREATE TABLE `Profiles` (
	`Id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Name` TEXT NOT NULL,
	`Type` INTEGER NOT NULL,
	`SealPrice` DECIMAL(8, 2) NOT NULL,
	`CornerPrice` DECIMAL(8, 2) NOT NULL
);
CREATE TABLE `ProfileColors` (
	`Id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Article` TEXT NOT NULL,
	`Name` TEXT NOT NULL
);
CREATE TABLE `ProfilePositions` (
	`ProfileId` INTEGER NOT NULL,
	`ColorId` INTEGER NOT NULL,
	`Price` DECIMAL(8, 2) NOT NULL,
	PRIMARY KEY (`ProfileId`, `ColorId`),
	FOREIGN KEY (`ProfileId`) REFERENCES `Profiles`(`Id`) ON DELETE CASCADE,
	FOREIGN KEY (`ColorId`) REFERENCES `ProfileColors`(`Id`) ON DELETE CASCADE
);
CREATE TABLE `Millings` (
	`Type` INTEGER NOT NULL,
	`ProfileType` INTEGER NOT NULL,
	`Name` TEXT,
	`Price` DECIMAL(8, 2) NOT NULL,
	PRIMARY KEY (`Type`, `ProfileType`)
);
CREATE TABLE `Prices` (`Id` INTEGER NOT NULL PRIMARY KEY, `Price` DECIMAL(8, 2) NOT NULL);

INSERT INTO `Prices` (`Id`, `Price`) VALUES (1, 450);